app = "livegpu"
primary_region = "ord"

[build]
  image = "ghcr.io/livebook-dev/livebook:0.11.3-cuda11.8"

[env]
  PORT = "8080"
  ELIXIR_ERL_OPTIONS = "-proto_dist inet6_tcp"
  LIVEBOOK_IP = "::"
  LIVEBOOK_HOME = "/data/livebook"
  LIVEBOOK_DATA_PATH = "/data/livebook"
  LIVEBOOK_ROOT_PATH = "/data/livebook"
  LIVEBOOK_APP_SERVICE_NAME = "Fly.io GPU demo"
  MIX_HOME="/data/mix"
  MIX_INSTALL_DIR="/data/mix"
  BUMBLEBEE_CACHE_DIR="/data/cache/bumblebee"
  XLA_TARGET = "cuda118"
  XLA_CACHE_DIR="/data/cache/xla"

[[mounts]]
  source = "livebook_data"
  destination = "/data"

[http_service]
  internal_port = 8080
  force_https = true

[[files]]
  guest_path = "/opt/nvidia/entrypoint.d/45-flyio.sh"
  local_path = "45-flyio.sh"
